- name: dcnm_fabric_group merged
  hosts: ndfc
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false

    ansible_httpapi_session_key: null
    ansible_persistent_connect_timeout: 10
    ansible_persistent_command_timeout: 300
    ansible_command_timeout: 300
  tasks:
    -   name: merged fabric group (dcnm_send)
        cisco.dcnm.dcnm_fabric_group:
            state: merged
            skip_validation: true
            config:
              - ANYCAST_GW_MAC: 2020.0000.00aa
                # BGP_RP_ASN: ""
                BGW_ROUTING_TAG: "54321"
                BORDER_GWY_CONNECTIONS: BAD_VALUE
                # BORDER_GWY_CONNECTIONS: Manual
                # BORDER_GWY_CONNECTIONS: Centralized_To_Route_Server
                # BORDER_GWY_CONNECTIONS: Direct_To_BGWS
                # CLOUDSEC_ALGORITHM: ""
                # CLOUDSEC_AUTOCONFIG: false
                # CLOUDSEC_ENFORCEMENT: ""
                # CLOUDSEC_KEY_STRING: ""
                # CLOUDSEC_REPORT_TIMER: ""
                DCI_SUBNET_RANGE: "10.10.1.0/24"
                DCI_SUBNET_TARGET_MASK: "30"
                DELAY_RESTORE: "300"
                # ENABLE_BGP_BFD: false
                # ENABLE_BGP_LOG_NEIGHBOR_CHANGE: false
                # ENABLE_BGP_SEND_COMM: false
                ENABLE_PVLAN: false
                # ENABLE_RS_REDIST_DIRECT: false
                ENABLE_SGT: "off"
                ENABLE_TRM_TRMv6: false
                EXT_FABRIC_TYPE: ""
                FABRIC_NAME: MCFG1
                FABRIC_TYPE: MCFG
                FF: MSD
                L2_SEGMENT_ID_RANGE: 30000-49000
                L3_PARTITION_ID_RANGE: 50000-59000
                # LOOPBACK100_IPV6_RANGE: ""
                LOOPBACK100_IP_RANGE: 10.10.0.0/24
                MSO_CONTROLER_ID: ""
                MSO_SITE_GROUP_NAME: ""
                # MS_IFC_BGP_AUTH_KEY_TYPE: ""
                # MS_IFC_BGP_PASSWORD: ""
                # MS_IFC_BGP_PASSWORD_ENABLE: false
                MS_LOOPBACK_ID: "100"
                MS_UNDERLAY_AUTOCONFIG: false
                PARENT_ONEMANAGE_FABRIC: ""
                PREMSO_PARENT_FABRIC: ""
                # RP_SERVER_IP: ""
                # RS_ROUTING_TAG: ""
                # SGT_ID_RANGE: ""
                # SGT_NAME_PREFIX: ""
                SGT_OPER_STATUS: "off"
                # SGT_PREPROVISION: false
                SGT_PREPROV_RECALC_STATUS: "empty"
                SGT_RECALC_STATUS: "empty"
                TOR_AUTO_DEPLOY: false
                # V6_DCI_SUBNET_RANGE: ""
                # V6_DCI_SUBNET_TARGET_MASK: ""
                VXLAN_UNDERLAY_IS_V6: false
                # default_network: Default_Network_Universal
                # default_pvlan_sec_network: ""
                # default_vrf: Default_VRF_Universal
                # enable_scheduled_backup: ""
                # network_extension_template: Default_Network_Extension_Universal
                # scheduled_time: ""
                # vrf_extension_template: Default_VRF_Extension_Universal
                seed_member:
                  cluster_name: "ND3"
                  fabric_name: "SITE3"
                # template_name: MSD_Fabric
        register: result
    -   debug:
            var: result
