- name: test dcnm_fabric_requests
  hosts: ndfc
  tasks:
    -   name: merged fabrics (dcnm_send)
        cisco.dcnm.dcnm_fabric:
            state: merged
            config:
             -   FABRIC_NAME: VXLAN_Fabric
                 FABRIC_TYPE: VXLAN_EVPN
                 BGP_AS: 65000
             -   FABRIC_NAME: MSD_Fabric
                 FABRIC_TYPE: VXLAN_EVPN_MSD
             -   FABRIC_NAME: LAN_Fabric
                 FABRIC_TYPE: LAN_CLASSIC
        register: result
    -   debug:
            var: result

