all:
  vars:
    ansible_user: "admin"
    ansible_password: "Cisco!2345"
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
  children:
    ndfc:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: cisco.dcnm.dcnm
      hosts:
        ndfc1:
          ansible_host: 172.22.150.244
