---
# This playbook can be used to execute integration tests for
# the role located in:
#
# tests/integration/targets/dcnm_image_policy
#
# Usage
#
# ansible-playbook dcnm_tests.yaml -i ../dynamic_inventory_env.py
#
# Modify the vars section with details for your testing setup.
#
# NOTES:
- hosts: ndfc
  gather_facts: no
  connection: ansible.netcommon.httpapi

  vars:
    # Uncomment ONE testcase to override environment variable NDFC_TESTCASE
    # testcase: dcnm_image_policy_deleted
    # testcase: dcnm_image_policy_deleted_all_policies
    # testcase: dcnm_image_policy_merged
    # testcase: dcnm_image_policy_overridden
    # testcase: dcnm_image_policy_query
    # testcase: dcnm_image_policy_replaced
    #
    # for dcnm_image_policy role
    image_policy_1: "KR5M"
    image_policy_2: "NR1F"
    epld_image_1: n9000-epld.10.2.5.M.img
    epld_image_2: n9000-epld.10.3.1.F.img
    nxos_image_1: n9000-dk9.10.2.5.M.bin
    nxos_image_2: n9000-dk9.10.3.1.F.bin
    nxos_release_1: 10.2.5_nxos64-cs_64bit
    nxos_release_2: 10.3.1_nxos64-cs_64bit

  roles:
    - dcnm_image_policy
